### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by adam1010** [Kount/kount-ris-php-sdk#19]
Has this been tested with php8 yet?  We're trying to use it but have run into a few errors:

```
 curl_setopt(): Argument #2 ($option) is not a valid cURL option at Kount/Ris/Request.php:318
```

Also, when trying to upgrade from 7.2 to 7.3 it's complaining that you're using an incompatible version of `sebastian/version`

Let me know if you need more details.

**Comment by toddfunke** [comment]
We are researching what we will need to do to support php8.  I hope to have an update soon.  Regarding sebastian/version, can you tell me what version of PHPUnit you are using?

**Comment by adam1010** [comment]
We're using latest phpunit 9.5 -- We were able to fix that sebastian/version issue on our side, so we've got 7.3.3 installed now -- so the issue we're seeing is now is just that `curl_setopt`  problem

**Comment by andeewoodward** [comment]
It appears the bug was due to an invalid curl configuration option. I have removed the invalid option (https://github.com/Kount/kount-ris-php-sdk/pull/20) and tested the fix in PHP 8 and it is no longer throwing this error.

**Comment by adam1010** [comment]
@toddfunke  I've confirmed PR https://github.com/Kount/kount-ris-php-sdk/pull/20 has fixed the issue. How soon can you get the a new release out?

**Comment by adam1010** [comment]
@toddfunke Here's the sebastian/version issue: 
![image](https://user-images.githubusercontent.com/3019544/111533521-1bce2800-8724-11eb-9a08-dd672dd2391d.png)

**Comment by toddfunke** [comment]
@adam1010,

Sorry for the delay in responding.  I am working with my team now to get this updated.  We had a few other updates that were in flight that are included with this one, so we needed to make sure it was properly tested.  My plan is to get this deployed today.

**Comment by adam1010** [comment]
@toddfunke @sanjeevitt @mmewara You guys forgot to bump the build version in `settings.ini` so it's still broken in 7.3.5 -- can you push 7.3.6 with the proper version increment?

https://github.com/Kount/kount-ris-php-sdk/blob/master/src/settings.ini#L15

**Comment by mmewara** [comment]
Hi @adam1010 we have increased the sdk version and updated release here. You can use release 7.3.6 and thanks for calling it out.

**Comment by adam1010** [comment]
Thanks @mmewara -- unfortunately now i'm running into another issue.  I'm able to install the 7.2.x into my php8 project, but when I try to use 7.3.6 it complains about this version conflict. I'm using the latest phpunit (9.5.1) -- it looks like the main thing you added as a requirement is php-code-coverage 7 -- it's now up to 9 -- are you able to try updating it to `>=7.0`  to see if that fixes it?

![image](https://user-images.githubusercontent.com/3019544/111708919-f87aaa00-8803-11eb-90b9-cb6258097d7c.png)

**Comment by adam1010** [comment]
Yeah that's the problem @mmewara @toddfunke  -- you're requiring `phpunit/php-code-coverage` version `7.x`, which doesn't support phpunit v9. Any reason you're making this a requirement to use your package?  I'm guessing it was accidentally just put in the wrong section `require` instead of `require-dev` -- in that case, you can leave it as requiring 7, just move it down a few lines in your `composer.json` into require-dev section.   Bump to 7.3.7?

https://github.com/Kount/kount-ris-php-sdk/blob/master/composer.json#L18

**Comment by mmewara** [comment]
> Yeah that's the problem @mmewara @toddfunke -- you're requiring `phpunit/php-code-coverage` version `7.x`, which doesn't support phpunit v9. Any reason you're making this a requirement to use your package? I'm guessing it was accidentally just put in the wrong section `require` instead of `require-dev` -- in that case, you can leave it as requiring 7, just move it down a few lines in your `composer.json` into require-dev section. Bump to 7.3.7?
> 
> https://github.com/Kount/kount-ris-php-sdk/blob/master/composer.json#L18


Hi @adam1010 let me verify this one, I will get back to you !

**Comment by adam1010** [comment]
@mmewara The `php-code-coverage` package is only needed for running unit tests -- which is only needed for developers of the plugin (it wasn't needed in v7.2.x, someone just accidentally included it when you moved to 7.3.x by putting it in the wrong section of the `composer.json` file).

I'd be happy to submit a PR to get this fixed. This is the package holding up our php8 deployment so please let me know how I can help get this done.

**Comment by mmewara** [comment]
Hi @adam1010 we are releasing the changes in the next few mins

**Comment by mmewara** [comment]
Hey, @adam1010 version 7.3.7 is released, please try it out !!!

**Comment by adam1010** [comment]
That did it! Thanks for your help.  Enjoy your weekend!
