### ISSUE TITLE
Composer installs can't set SALT_PHRASE

### ISSUE THREAD

**Issue by Silarn** [Kount/kount-ris-php-sdk#5]
Because of the addition of the SALT_PHRASE parameter, composer installs of the SDK will not work when needing the Kount_Util_Khash class. This is because the Khash class does not allow you to pass in custom settings values in the constructor, while other classes, such as Kount_Ris_Request, do.

Thus, when you use the Kount_Util_Khash::hash function, it always loads the SALT_PHRASE from the settings.ini file. However, the settings.ini file is going to be overwritten any time you update the composer package (nor will it, of course, preserve this setting across different composer installs). This makes using this file to set settings unfeasible.

The Kount_Util_Khash class needs to be able to accept custom settings.

**Comment by Silarn** [comment]
In fact, I'm not actually sure if we're even using a salt right now. Up to this point, I don't believe we had a salt set. Since the API triggers an error if no salt is set, this means we can't generate the PTOK - salted or not.

**Comment by preslav-anev** [comment]
@Silarn I am aware of this issue and I've prepared a pull-request soon to be merged with a fix for this situatuon. We basically will allow custom settings for the Kount_Util_Khash, since as you've noticed providing the settings only from the default settings.ini isn't ideal in all cases.

In the meantime you can check the wiki documentation page for more detailed information.
[Wiki page here](https://github.com/Kount/kount-ris-php-sdk/wiki/Add-Settings-Configuration)

**Comment by preslav-anev** [comment]
@Silarn, 

A new version(6.5.3) of Kount RIS PHP SDK has been released with functionality for accepting custom settings. Now you can set up your own settings file add the required configurations there.
Detailed information on how to use this functionality has been added in the documentation [documentation here](https://github.com/Kount/kount-ris-php-sdk/wiki/Add-Settings-Configuration).

**Comment by Silarn** [comment]
Are you intentionally removing the ability to pass custom settings programatically (instead of via a settings file)? The Kount_Ris_Request_Update|Inquiry classes still suggest passing a '$customSettings' object, but instead this maps to the $khashObject on the parent Kount_Ris_Request. This also becomes incredibly redundant as you have to instantiate a custom settings file both to the passed Khash class in addition to the instantiated Request class.

(In other words, it seems to make more sense to automatically instantiate the custom Khash in the Request object if the $settings parameter is set instead of requiring both.)

**Comment by Silarn** [comment]
This ultimately also precludes the ability to pull these settings from a database or something like that - requiring a hard settings file to store everything.

**Comment by Silarn** [comment]
I've created a fork which allows programatic settings as well as a custom file. It also simplifies some of the function calls.
